{
  id:'dfw-blk-men-futureready', title:'FutureReady: Defining the Future Workplace', city:'DFW', area:'Frisco / Dallas North Tollway', category:'hybrid',
  start:'2026-07-22T17:00:00', end:'2026-07-22T19:00:00', displayTime:'Wed, Jul 22 · 5:00–7:00 PM CT',
  venue:'TIAA Office, 3965 Dallas Pkwy, Frisco', score:89, tags:['BLACK-CENTERED','TECH','AI','NETWORK','CAPACITY-RISK'],
  audience:'BLK Men in Tech describes the event for professionals, emerging leaders and executives discussing AI, culture, career growth, belonging and the future workplace.',
  why:'A credible Black professional-tech room with a named corporate partner, structured panel content, food, drinks and intentional networking. The value is high; the weekday Frisco logistics are the constraint.',
  cost:'RSVP required; advertised price not shown', status:'CAPACITY LIMITED — EVENT TOMORROW', action:'RSVP ONLY IF PTO / DFW OVERNIGHT IS REALISTIC',
  fit:{level:'hard', label:'Not possible after an 8–5 San Antonio workday', note:'A 5 PM Frisco start requires leaving Heritage Plaza around noon. Leaving work at 5 PM would put arrival near or after the event end. Treat this as PTO, an existing DFW trip, or skip.'},
  scores:{career:5,social:4,black:5,writing:1,value:5},
  officialUrl:'https://cu.linkedin.com/company/blk-men-in-tech',
  municipality:'Frisco', neighborhood:'Dallas North Tollway · Stonebriar corridor', visualTone:'tech', visualIcon:'↗',
  travel:{etaMin:255,etaMax:300,parking:20,arrivalBuffer:30,destination:'TIAA, 3965 Dallas Pkwy, Frisco, TX 75034',overnight:true,note:'Recommended plan: arrive in DFW the previous evening or take PTO and leave Heritage Plaza by approximately 11:45 AM–12:15 PM.'},
  organizer:'BLK Men in Tech; powered by TIAA', format:'Professional panel, food, drinks and networking', bestFor:'Black tech professionals seeking career-growth and executive-network access', goAlone:'Yes — the event is explicitly designed for professional connection',
  ageAccess:'Professional office event; RSVP acceptance and venue access rules apply', attire:'Business casual / polished tech-professional',
  networkingObjective:'Meet one product or engineering leader and one professional working on AI adoption, culture or workforce strategy.',
  priceNotes:'The organizer states capacity is limited. Confirm acceptance before any travel; do not drive without a valid RSVP.',
  verifiedOn:'Organizer LinkedIn event announcement checked July 21, 2026'
},
{
  id:'aus-afs-short-grant-webinar', title:'AFS Grant for Short Films — Application + Webinar', city:'Austin', area:'Online / Texas-wide', category:'career',
  start:'2026-07-30T18:00:00', end:'2026-07-30T19:00:00', displayTime:'Thu, Jul 30 · 6:00–7:00 PM CT · applications open Jul 23',
  venue:'Online via Zoom', score:90, tags:['TV/FILM','WRITING','GRANT','SUBMIT','FREE','DEADLINE'],
  audience:'Texas-based filmmakers developing short films under 40 minutes in pre-production, production or post-production.',
  why:'A direct, credible funding path for a Texas short-film proof of concept. AFS reports up to $10,000 cash support plus possible in-kind awards, with a competitive historical funding rate.',
  cost:'Free webinar; grant application fee not stated', status:'APPLICATION OPENS JUL 23 · DEADLINE AUG 27', action:'RSVP; APPLY ONLY WITH A REAL SHORT-FILM TEAM AND PACKAGE',
  fit:{level:'clear', label:'Easy after-work online fit', note:'The 6 PM online session fits the protected 8–5 workday. Block 5:45–7:15 PM for login, notes and immediate follow-up.'},
  scores:{career:5,social:1,black:2,writing:4,value:5},
  officialUrl:'https://www.austinfilm.org/event/2026-shorts-webinar1/',
  municipality:'Online', neighborhood:'Remote · Texas applicants', visualTone:'career', visualIcon:'⌛', travel:{mode:'none'},
  organizer:'Austin Film Society', format:'Online grant-information webinar and Q&A', bestFor:'Texas filmmakers with a concrete short film and production plan', goAlone:'Not applicable — online',
  networkingObjective:'Use the Q&A to clarify one project-specific eligibility, sample or budget question—not to pitch the story broadly.',
  breakInMove:'Convert one strong television concept, scene or character conflict into a producible short-film proof of concept only if you can identify a director/producer plan, sample work and realistic budget.',
  priceNotes:'Applications open July 23 and close August 27. AFS says short-film projects may request up to $10,000 cash for eligible production stages; incorrect video samples can make an application ineligible.',
  verifiedOn:'Official Austin Film Society grant and webinar pages checked July 21, 2026',
  milestones:[{date:'2026-07-23',label:'AFS short-film grant opens',type:'deadline'},{date:'2026-08-27',label:'AFS short-film grant deadline',type:'deadline'}]
},
{
  id:'aus-afrobeats-happiness-jul25', title:'Afrobeats & Happiness — Austin', city:'Austin', area:'Downtown Austin / Lavaca Street', category:'social',
  start:'2026-07-25T21:00:00', end:'2026-07-26T02:00:00', displayTime:'Sat, Jul 25 · 9:00 PM–2:00 AM CT',
  venue:'Twins Nightclub, 315 Lavaca St', score:84, tags:['AFROBEATS','AMAPIANO','PARTY','SOCIAL','21+','CAPACITY-RISK'],
  audience:'The organizer describes an upscale dance-floor experience for young professionals featuring Afrobeats, Amapiano, dancehall, hip-hop and international music.',
  why:'A true pure-social option with dancing, a defined music identity and a professional crowd positioning. It is materially different from generic bar nightlife and works around the weekday schedule.',
  cost:'Entry tiers displayed starting at $0; higher tiers may apply', status:'FEW TICKETS LEFT', action:'GO; CLAIM TICKET BEFORE SATURDAY',
  fit:{level:'clear', label:'Practical Saturday evening', note:'From Heritage Plaza, plan approximately 75–100 minutes plus downtown parking. Leave around 6:55–7:20 PM to arrive near 8:30 PM without rushing.'},
  scores:{career:1,social:5,black:3,writing:1,value:5},
  officialUrl:'https://www.eventbrite.com/e/afrobeats-happiness-austintx-tickets-1992732366150',
  municipality:'Austin', neighborhood:'Downtown · Warehouse District', visualTone:'social', visualIcon:'♬',
  travel:{etaMin:75,etaMax:100,parking:25,arrivalBuffer:30,destination:'Twins Nightclub, 315 Lavaca St, Austin, TX 78701',note:'Recommended Heritage Plaza departure: approximately 6:55–7:20 PM for an 8:30 PM arrival target.'},
  organizer:'Culture Curators', format:'Upscale late-night dance party', bestFor:'Pure social, dancing and meeting other nightlife-oriented young professionals', goAlone:'Yes, if you are comfortable initiating conversation before the dance floor peaks',
  ageAccess:'21+', attire:'Trendy and fashionable; no sports attire, jerseys, hoodies, tank tops, bandanas or casual open-toe shoes per organizer',
  networkingObjective:'Pure social: arrive before 10 PM, initiate three conversations before the room becomes loud, and avoid business-pitch energy.',
  priceNotes:'No refunds. Eventbrite displayed a starting tier at $0 and a few-tickets-left indicator; verify the live checkout tier before leaving.',
  verifiedOn:'Eventbrite organizer listing checked July 21, 2026'
},
{
  id:'hou-bfusa-mixer-jul28', title:'BFUSA Houston Mixer 2026', city:'Houston', area:'Downtown Houston / Main Street', category:'hybrid',
  start:'2026-07-28T20:30:00', end:'2026-07-29T02:00:00', displayTime:'Tue, Jul 28 · 8:30 PM–2:00 AM CT',
  venue:'Dome Nightclub, 1720 Main St', score:83, tags:['BLACK-CENTERED','AVIATION','NETWORK','PARTY','SOCIAL','21+'],
  audience:'Black Flight Attendants USA is celebrating ten years with Black aviation professionals and attendees connected to the flight-attendant community.',
  why:'A legitimate Black professional-affinity event that converts into nightlife. It offers better conversation structure than a generic club, although its narrow aviation focus and Tuesday timing reduce fit.',
  cost:'Approximately $48.19 general admission shown by a secondary ticket index; verify at official checkout', status:'ON SALE · NO REFUNDS', action:'MAYBE — GO ONLY FOR AVIATION / BLACK-PROFESSIONAL SOCIAL VALUE',
  fit:{level:'soft', label:'Borderline after-work Houston drive', note:'A direct 5 PM departure from Heritage Plaza could reach downtown Houston around 8:10–8:40 PM before parking. Any work overrun, meal stop or traffic spike makes you late. Safer plan: leave by 4:30 PM or stay overnight.'},
  scores:{career:3,social:5,black:5,writing:1,value:3},
  officialUrl:'https://www.eventbrite.com/e/bfusa-houston-mixer-2026-tickets-1987283442272',
  municipality:'Houston', neighborhood:'Downtown · Main Street', visualTone:'hybrid', visualIcon:'∞',
  travel:{etaMin:175,etaMax:205,parking:25,arrivalBuffer:20,destination:'Dome Nightclub, 1720 Main St, Houston, TX 77002',overnight:true,note:'Recommended Heritage Plaza departure: 4:30–4:50 PM. Leaving at 5 PM is possible only with favorable traffic and no stops.'},
  organizer:'Black Flight Attendants USA', format:'Industry-affinity mixer followed by nightclub socializing', bestFor:'Black aviation professionals and high-energy affinity networking', goAlone:'Yes — shared industry identity supplies a natural conversation opener',
  ageAccess:'21+', attire:'Nightlife polished; verify any venue-specific dress code',
  networkingObjective:'Meet two people outside your immediate field and ask how their aviation careers intersect with media, technology, travel or creator work.',
  priceNotes:'No refunds. The exact official checkout total was not exposed in the indexed Eventbrite page; verify taxes and fees before purchase.',
  verifiedOn:'Official Eventbrite listing and secondary price index checked July 21, 2026'
},
{
  id:'dfw-afrosocalove-aug8', title:'AfroSocaLove: Dallas One Love Festival', city:'DFW', area:'Downtown Dallas / City Hall', category:'social',
  start:'2026-08-08T17:00:00', end:'2026-08-08T22:00:00', displayTime:'Sat, Aug 8 · 5:00–10:00 PM CT',
  venue:'Dallas City Hall, 1500 Marilla St', score:88, tags:['AFROBEATS','CARIBBEAN','AFRO-LATIN','BLACK-CULTURE','SOCIAL','FESTIVAL'],
  audience:'A multicultural festival audience gathering around African American, Caribbean, African and Afro-Latin food, music, vendors and community programming.',
  why:'A strong pure-social DFW option with walk-around vendors, food and music—more conversation-friendly than a seated show and more culturally aligned than a generic festival.',
  cost:'Current organizer page shows $20 sale price for general entry; broader tiers range roughly $15–$1,000', status:'LOW STOCK INDICATOR ON ORGANIZER SITE', action:'BUY GA; SKIP PREMIUM TIERS UNLESS ATTENDING WITH A GROUP',
  fit:{level:'clear', label:'Saturday trip; long drive', note:'Plan 4¼–5 hours from Heritage Plaza plus parking. Leave around 11:15 AM–12:00 PM for a 4:15 PM arrival target. An overnight is safer if staying through 10 PM.'},
  scores:{career:1,social:5,black:4,writing:1,value:4},
  officialUrl:'https://afrosocalovesupply.com/products/dallas-one-love-festival',
  municipality:'Dallas', neighborhood:'Downtown · Government District', visualTone:'social', visualIcon:'✦',
  travel:{etaMin:255,etaMax:300,parking:35,arrivalBuffer:45,destination:'Dallas City Hall, 1500 Marilla St, Dallas, TX 75201',overnight:true,note:'Recommended Heritage Plaza departure: approximately 11:15 AM–12:00 PM. Consider a hotel rather than driving back after a five-hour festival.'},
  organizer:'Afro Soca Love', format:'Outdoor cultural festival with DJs, food, vendors and entertainment', bestFor:'Pure social, diaspora culture and organic walk-around conversation', goAlone:'Yes — vendors, food and music create easy conversation openings; a small group improves the long-trip economics',
  ageAccess:'Organizer pages conflict between all-ages and 21+ versions; verify the ticket selected. Children 16 and under are listed free on the organizer store page.',
  attire:'Festival-forward / dress to impress; weather-ready shoes',
  networkingObjective:'Pure social: meet one vendor, one attendee through a food or music conversation, and one organizer or community partner.',
  priceNotes:'No refunds. Paid/free parking details conflict across duplicate listings; use the organizer checkout and final attendee instructions as the source of truth.',
  verifiedOn:'Official AfroSocaLove organizer store and Eventbrite listings checked July 21, 2026'
}