{
 id:'national-sundance-episodic-lab-2027',title:'Sundance Institute 2027 Episodic Lab + Intensive',city:'National',area:'Remote application / in-person lab',category:'career',
 start:'2026-08-25T23:59:00',end:'2026-08-25T23:59:00',displayTime:'Deadline Tue, Aug 25 · exact FilmFreeway cutoff should be verified',
 venue:'Application online; selected in-person Lab at Dunaway Gardens, Apr 15–20, 2027',score:98,tags:['TV/FILM','WRITING','PITCH','SUBMIT','MAJOR','DEADLINE'],
 audience:'Writers age 18+ with a complete original scripted-series pilot. Applicants of any nationality are eligible; writing teams of up to two are allowed.',
 why:'Direct episodic-development access through showrunner mentorship, one-on-one story meetings, craft workshops, simulated writers rooms, continuing support and potential industry introductions.',
 cost:'$50 nonrefundable application fee; selected Lab artists receive covered travel, food and accommodations',status:'APPLICATION OPEN · DEADLINE AUG 25',action:'APPLY ONLY WITH A POLISHED ORIGINAL PILOT AND COMPLETE SERIES PACKAGE',
 fit:{level:'clear',label:'Remote application; fully compatible with the 8–5 workday',note:'Internal target: lock the pilot by Aug 14 and submit by Aug 21.'},
 scores:{career:5,social:2,black:3,writing:5,value:5},officialUrl:'https://www.sundance.org/programs/episodic-storytelling',
 municipality:'Remote',neighborhood:'National opportunity',visualTone:'career',visualIcon:'✍',travel:{mode:'none'},organizer:'Sundance Institute',
 format:'Competitive episodic writing Lab and virtual Intensive',bestFor:'Emerging television writers with a completed original pilot and a clear series engine',goAlone:'Not applicable — application opportunity',
 networkingObjective:'If selected, enter with a concise staffing identity, clear revision priorities and showrunner-level craft questions.',
 breakInMove:'Complete the pilot, 50-word logline, 500-word pilot synopsis, 500-word series overview, 250-word personal statement and 250-word thematic statement. Make the repeatable episode engine explicit.',
 priceNotes:'A separate $50 fee applies to each project. Projects cannot already be produced, sold, distributed or currently set up or pitching in the U.S.',
 verifiedOn:'Official Sundance Institute pages checked July 22, 2026',milestones:[{date:'2026-08-14',label:'Internal pilot-lock target',type:'deadline'},{date:'2026-08-21',label:'Recommended submission target',type:'deadline'},{date:'2026-08-25',label:'Sundance Episodic deadline',type:'deadline'}]
},
{
 id:'hou-marketing-for-culture-2026',title:'Marketing For The Culture Summit 2026',city:'Houston',area:'East Downtown / EaDo',category:'hybrid',
 start:'2026-08-27T08:30:00',end:'2026-08-27T17:00:00',displayTime:'Thu, Aug 27 · 8:30 AM–5:00 PM CT · kickoff reception Wed, Aug 26, 6:00–8:00 PM',
 venue:'800 Sampson St, Houston',score:96,tags:['BLACK-CENTERED','MARKETING','AI','DATA','CREATOR-ECONOMY','NETWORK','CAPACITY-RISK'],
 audience:'Black marketers, creatives and entrepreneurs focused on career growth, business growth, data, AI and cultural relevance.',
 why:'Exceptionally aligned with MX Ventures: data-driven marketing, creator economy, media, AI, analytics and a credible Black professional community. Speaker submissions are open.',
 cost:'Tickets advertised from $68.53; higher tiers shown up to roughly $160.83',status:'GOING FAST · SPEAKER SUBMISSIONS OPEN',action:'BUY STANDARD TICKET; SUBMIT A SPEAKER PROPOSAL',
 fit:{level:'hard',label:'Requires PTO and likely a Houston overnight',note:'Travel after work Wednesday for the kickoff, stay overnight and use PTO Thursday.'},
 scores:{career:5,social:4,black:5,writing:2,value:5},officialUrl:'https://www.aa-ma.org/mftcs',municipality:'Houston',neighborhood:'EaDo · East Downtown',visualTone:'hybrid',visualIcon:'◆',
 travel:{etaMin:170,etaMax:205,parking:25,arrivalBuffer:30,destination:'800 Sampson St, Houston, TX 77003',overnight:true,note:'Leave Heritage Plaza Wednesday around 2:15–2:45 PM for the 6 PM kickoff; stay overnight and take PTO Thursday.'},
 organizer:'African-American Marketing Association',format:'Kickoff reception, one-day summit, panels, meals and professional networking',bestFor:'Black marketers, analytics professionals, creators, entrepreneurs and founders',goAlone:'Yes',
 ageAccess:'Professional conference; ticket required',attire:'Polished business casual / creative professional',networkingObjective:'Meet one measurement leader, one creator-economy operator and one potential MX Ventures client or partner.',
 breakInMove:'Submit a speaker proposal on privacy-safe customer intelligence, analytics for culturally relevant growth, or AI governance for lean marketing teams.',
 priceNotes:'Live ticket inventory is available; refunds were listed up to seven days before the summit.',verifiedOn:'Official organizer pages checked July 22, 2026'
},
{
 id:'hou-uno-social-club-aug6',title:'UNO Social Club — Houston',city:'Houston',area:'Houston Heights / North Main',category:'social',
 start:'2026-08-06T18:00:00',end:'2026-08-06T21:00:00',displayTime:'Thu, Aug 6 · 6:00–9:00 PM CT',venue:"Dan Electro's, 1031 E 24th St",score:83,
 tags:['SOCIAL','FREE','GAMES','21+','RSVP','CAPACITY-RISK'],audience:'A 21+ community social built around UNO gameplay, friendly competition and low-pressure conversation.',
 why:'Structured gameplay creates natural conversation and makes attending alone easier than a generic bar or nightclub.',
 cost:'Free with RSVP; admission first-come, first-served and RSVP does not guarantee entry',status:'FREE RSVP · CAPACITY RISK',action:'RSVP; ATTEND ONLY WITH EARLY RELEASE OR AN EXISTING HOUSTON PLAN',
 fit:{level:'hard',label:'Not practical after a normal 8–5 San Antonio workday',note:'A 5 PM departure likely reaches the venue near the event end. Leave around 2:00–2:30 PM or skip.'},
 scores:{career:1,social:5,black:1,writing:1,value:5},officialUrl:'https://danelectros.com/events',municipality:'Houston',neighborhood:'Houston Heights · North Main corridor',visualTone:'social',visualIcon:'◫',
 travel:{etaMin:175,etaMax:205,parking:20,arrivalBuffer:30,destination:"Dan Electro's, 1031 E 24th St, Houston, TX 77009",overnight:false,note:'Recommended Heritage Plaza departure: approximately 2:00–2:30 PM.'},
 organizer:'UNO Social Club; hosted at Dan Electro’s',format:'Free card-game social',bestFor:'Pure social connection and attending alone',goAlone:'Yes — gameplay creates immediate interaction',ageAccess:'21+',attire:'Casual social',
 networkingObjective:'Join a table quickly, learn three names and invite one promising connection to another low-pressure event.',priceNotes:'Arrive before doors; RSVP does not guarantee admission.',verifiedOn:'Official venue calendar checked July 22, 2026'
},
{
 id:'aus-afs-short-grant-webinar',title:'AFS Grant for Short Films — Application + Webinar',city:'Austin',area:'Online / Texas-wide',category:'career',
 start:'2026-07-30T18:00:00',end:'2026-07-30T19:00:00',displayTime:'Thu, Jul 30 · 6:00–7:00 PM CT · applications opened Jul 23',venue:'Online via Zoom',score:90,
 tags:['TV/FILM','WRITING','GRANT','SUBMIT','FREE','DEADLINE'],audience:'Texas-based filmmakers developing short films under 40 minutes in pre-production, production or post-production.',
 why:'A credible Texas funding path for a short-film proof of concept, with up to $10,000 cash support plus potential in-kind awards.',
 cost:'Free webinar; grant application fee not stated',status:'APPLICATION OPEN · DEADLINE AUG 27',action:'REGISTER; APPLY ONLY WITH A REAL SHORT-FILM TEAM AND PACKAGE',
 fit:{level:'clear',label:'Easy after-work online fit',note:'Block 5:45–7:15 PM for login, notes and follow-up.'},scores:{career:5,social:1,black:2,writing:4,value:5},
 officialUrl:'https://www.austinfilm.org/event/2026-shorts-webinar1/',municipality:'Online',neighborhood:'Remote · Texas applicants',visualTone:'career',visualIcon:'⌛',travel:{mode:'none'},
 organizer:'Austin Film Society',format:'Online grant webinar and Q&A',bestFor:'Texas filmmakers with a concrete short and production plan',goAlone:'Not applicable — online',
 networkingObjective:'Use the Q&A to clarify one project-specific eligibility, sample or budget question.',breakInMove:'Use one strong television character or conflict as a producible short-film proof of concept only with a real director/producer plan, work sample and budget.',
 priceNotes:'Applications opened July 23 and close August 27. Incorrect or ineligible samples can disqualify an application.',verifiedOn:'Official AFS pages checked July 23, 2026',
 milestones:[{date:'2026-08-27',label:'AFS short-film grant deadline',type:'deadline'}]
},
{
 id:'aus-afrobeats-happiness-jul25',title:'Afrobeats & Happiness — Austin',city:'Austin',area:'Downtown Austin / Lavaca Street',category:'social',
 start:'2026-07-25T21:00:00',end:'2026-07-26T02:00:00',displayTime:'Sat, Jul 25 · 9:00 PM–2:00 AM CT',venue:'Twins Nightclub, 315 Lavaca St',score:84,
 tags:['AFROBEATS','AMAPIANO','PARTY','SOCIAL','21+','CAPACITY-RISK'],audience:'An upscale dance-floor experience for young professionals featuring Afrobeats, Amapiano, dancehall, hip-hop and international music.',
 why:'A true pure-social option with dancing, a defined music identity and professional-crowd positioning.',
 cost:'Entry tiers displayed starting at $0; higher tiers may apply',status:'FEW TICKETS LEFT',action:'GO; CLAIM A TICKET BEFORE SATURDAY',
 fit:{level:'clear',label:'Practical Saturday evening',note:'Leave Heritage Plaza around 6:55–7:20 PM for an 8:30 PM arrival target.'},scores:{career:1,social:5,black:3,writing:1,value:5},
 officialUrl:'https://www.eventbrite.com/e/afrobeats-happiness-austintx-tickets-1992732366150',municipality:'Austin',neighborhood:'Downtown · Warehouse District',visualTone:'social',visualIcon:'♬',
 travel:{etaMin:75,etaMax:100,parking:25,arrivalBuffer:30,destination:'Twins Nightclub, 315 Lavaca St, Austin, TX 78701',note:'Recommended departure: 6:55–7:20 PM.'},
 organizer:'Culture Curators',format:'Upscale late-night dance party',bestFor:'Pure social, dancing and meeting nightlife-oriented young professionals',goAlone:'Yes, with early conversation before the dance floor peaks',
 ageAccess:'21+',attire:'Trendy and fashionable; no sports attire, jerseys, hoodies, tank tops, bandanas or casual open-toe shoes',networkingObjective:'Arrive before 10 PM and initiate three conversations before the room becomes loud.',
 priceNotes:'No refunds. Verify the live checkout tier before leaving.',verifiedOn:'Official Eventbrite organizer listing checked July 23, 2026'
},
{
 id:'hou-bfusa-mixer-jul28',title:'BFUSA Houston Mixer 2026',city:'Houston',area:'Downtown Houston / Main Street',category:'hybrid',
 start:'2026-07-28T20:30:00',end:'2026-07-29T02:00:00',displayTime:'Tue, Jul 28 · 8:30 PM–2:00 AM CT',venue:'Dome Nightclub, 1720 Main St',score:83,
 tags:['BLACK-CENTERED','AVIATION','NETWORK','PARTY','SOCIAL','21+'],audience:'Black Flight Attendants USA is celebrating ten years with Black aviation professionals and attendees connected to the flight-attendant community.',
 why:'A legitimate Black professional-affinity event that converts into nightlife, though its narrow focus and Tuesday timing reduce fit.',
 cost:'Approximately $48.19 GA shown by a secondary index; verify live checkout',status:'ON SALE · NO REFUNDS',action:'MAYBE — GO ONLY FOR AVIATION / BLACK-PROFESSIONAL SOCIAL VALUE',
 fit:{level:'soft',label:'Borderline after-work Houston drive',note:'Leave by 4:30–4:50 PM; a 5 PM departure is traffic-dependent.'},scores:{career:3,social:5,black:5,writing:1,value:3},
 officialUrl:'https://www.eventbrite.com/e/bfusa-houston-mixer-2026-tickets-1987283442272',municipality:'Houston',neighborhood:'Downtown · Main Street',visualTone:'hybrid',visualIcon:'∞',
 travel:{etaMin:175,etaMax:205,parking:25,arrivalBuffer:20,destination:'Dome Nightclub, 1720 Main St, Houston, TX 77002',overnight:true,note:'Recommended departure: 4:30–4:50 PM.'},
 organizer:'Black Flight Attendants USA',format:'Industry-affinity mixer followed by nightclub socializing',bestFor:'Black aviation professionals and high-energy affinity networking',goAlone:'Yes',
 ageAccess:'21+',attire:'Nightlife polished; verify venue rules',networkingObjective:'Meet two people outside your field and ask how aviation intersects with media, technology, travel or creator work.',
 priceNotes:'No refunds; verify taxes and fees before purchase.',verifiedOn:'Official Eventbrite listing checked July 21, 2026'
},
{
 id:'dfw-afrosocalove-aug8',title:'AfroSocaLove: Dallas One Love Festival',city:'DFW',area:'Downtown Dallas / City Hall',category:'social',
 start:'2026-08-08T17:00:00',end:'2026-08-08T22:00:00',displayTime:'Sat, Aug 8 · 5:00–10:00 PM CT',venue:'Dallas City Hall, 1500 Marilla St',score:88,
 tags:['AFROBEATS','CARIBBEAN','AFRO-LATIN','BLACK-CULTURE','SOCIAL','FESTIVAL'],audience:'A multicultural audience gathering around African American, Caribbean, African and Afro-Latin food, music, vendors and community programming.',
 why:'A strong pure-social DFW option with walk-around vendors, food and music—more conversation-friendly than a seated show.',
 cost:'Organizer page shows approximately $20 general entry',status:'LOW STOCK INDICATOR',action:'BUY GA; SKIP PREMIUM TIERS UNLESS ATTENDING WITH A GROUP',
 fit:{level:'clear',label:'Saturday trip; long drive',note:'Leave Heritage Plaza around 11:15 AM–noon and consider an overnight.'},scores:{career:1,social:5,black:4,writing:1,value:4},
 officialUrl:'https://afrosocalovesupply.com/products/dallas-one-love-festival',municipality:'Dallas',neighborhood:'Downtown · Government District',visualTone:'social',visualIcon:'✦',
 travel:{etaMin:255,etaMax:300,parking:35,arrivalBuffer:45,destination:'Dallas City Hall, 1500 Marilla St, Dallas, TX 75201',overnight:true,note:'Recommended departure: 11:15 AM–noon.'},
 organizer:'Afro Soca Love',format:'Outdoor cultural festival with DJs, food, vendors and entertainment',bestFor:'Pure social, diaspora culture and organic walk-around conversation',goAlone:'Yes; a small group improves the trip economics',
 ageAccess:'Organizer pages conflict between all-ages and 21+; verify selected ticket',attire:'Festival-forward; weather-ready shoes',networkingObjective:'Meet one vendor, one attendee and one organizer or community partner.',
 priceNotes:'No refunds. Parking and age details conflict across listings; follow final organizer instructions.',verifiedOn:'Official organizer listings checked July 21, 2026'
},
{
 id:'aus-apa-producer-bash-jul25',title:'Austin Producer Alliance — Producer Bash + Battle',city:'Austin',area:'Highland / ACC Highland',category:'career',
 start:'2026-07-25T13:30:00',end:'2026-07-25T17:30:00',displayTime:'Sat, Jul 25 · 1:30–5:30 PM CT · after-hours follows',venue:'ACC Highland Campus, Building 2000 Room 1446',score:78,
 tags:['CREATOR-ECONOMY','MUSIC','PRODUCTION','NETWORK','FREE'],audience:'Music producers of all experience levels and genres creating, sharing and voting on original tracks in a collaborative setting.',
 why:'A hands-on creative-networking room with structured activity, repeated interaction and a listening session. It is stronger for creator-community access than for television writing.',
 cost:'No ticket price stated on the organizer listing',status:'ACTIVE REGISTRATION',action:'GO IF CREATOR-ECONOMY AND MUSIC-PRODUCTION NETWORKING MATTER',
 fit:{level:'clear',label:'Practical Saturday afternoon',note:'Leave Heritage Plaza around 11:20 AM–noon for a 1 PM arrival and parking buffer.'},scores:{career:4,social:4,black:1,writing:2,value:5},
 officialUrl:'https://www.meetup.com/austin-producer-alliance/events/315092159/',municipality:'Austin',neighborhood:'Highland · ACC campus',visualTone:'career',visualIcon:'♫',
 travel:{etaMin:75,etaMax:100,parking:15,arrivalBuffer:30,destination:'ACC Highland Campus, 6101 Highland Campus Dr, Austin, TX',note:'Recommended departure: 11:20 AM–noon.'},
 organizer:'Austin Producer Alliance',format:'Collaborative beat-making challenge, listening party and after-hours networking',bestFor:'Music producers, audio creators and creator-economy networking',goAlone:'Yes — the production exercise supplies instant interaction',
 attire:'Casual creative',networkingObjective:'Meet one producer, one audio engineer and one creator who works across music, film or branded content.',verifiedOn:'Official Meetup organizer listing checked July 23, 2026'
},
{
 id:'hou-challenging-brown-jul26',title:'Challenging Brown — Vanguard Series',city:'Houston',area:'Midtown / MATCH',category:'career',
 start:'2026-07-26T15:00:00',end:'2026-07-26T17:00:00',displayTime:'Sun, Jul 26 · 3:00 PM CT',venue:'MATCH, Matchbox 1, 3400 Main St',score:79,
 tags:['BLACK-CULTURE','THEATER','WRITING','TV/FILM'],audience:'Audiences interested in bold contemporary Black theater and a story about the first Black teacher at an all-white Texas high school in 1967.',
 why:'A credible new-work presentation from a playwright recognized by the Fade To Black Arts Festival and Ensemble Theatre readings. No Q&A or reception is advertised.',
 cost:'$40 regular; $30 seniors/students; $5 box-office fee; 10% group discount for 10+',status:'ON SALE · ALL SALES FINAL',action:'MAYBE — CHOOSE ONLY IF BLACK THEATER AND STORY CRAFT OUTRANK THE DANCE FESTIVAL',
 fit:{level:'clear',label:'Possible Sunday trip, but requires an early departure',note:'Leave Heritage Plaza around 10:45–11:20 AM for a 2:30 PM seating target.'},scores:{career:3,social:2,black:5,writing:4,value:3},
 officialUrl:'https://matchouston.org/events/2026/challenging-brown/sunday-july-26-300-pm',municipality:'Houston',neighborhood:'Midtown · Main Street',visualTone:'career',visualIcon:'◼',
 travel:{etaMin:175,etaMax:205,parking:20,arrivalBuffer:30,destination:'MATCH, 3400 Main St, Houston, TX 77002',note:'Recommended departure: 10:45–11:20 AM.'},
 organizer:'Shabach Enterprise',format:'Live theater presentation in the Vanguard Series',bestFor:'Black theater, writing craft and culturally specific storytelling',goAlone:'Yes, but direct networking is not promised',
 ageAccess:'Suitable for all audiences',attire:'Smart casual',networkingObjective:'Study the protagonist’s dramatic engine and speak with attendees only if an organic post-show opportunity appears.',
 priceNotes:'All sales final; late seating is discretionary.',verifiedOn:'Official MATCH page checked July 23, 2026'
},
{
 id:'dfw-black-outside-aug1',title:'Black & Outside Block Party',city:'DFW',area:'Dallas / venue transition',category:'social',
 start:'2026-08-01T14:00:00',end:'2026-08-01T22:30:00',displayTime:'Sat, Aug 1 · 2:00–10:30 PM CT',venue:'Royal Lane Studios; final address and parking to be reconfirmed',score:88,
 tags:['BLACK-CENTERED','BLACK-CULTURE','SOCIAL','NETWORK','VENDORS','ALL-AGES'],audience:'A celebration of Black culture, community and creativity with Black-owned businesses, DJs, food vendors, games and networking.',
 why:'A long-duration, activity-based environment that supports natural conversation better than a generic nightclub or seated event.',
 cost:'Live ticket price not exposed in the indexed organizer page',status:'VENUE TRANSITION · VERIFY FINAL ADDRESS BEFORE TRAVEL',action:'WATCH, THEN GO AFTER FINAL VENUE CONFIRMATION',
 fit:{level:'clear',label:'Saturday trip; long drive and venue confirmation required',note:'Do not leave San Antonio until the organizer confirms the final address and parking.'},scores:{career:2,social:5,black:5,writing:1,value:4},
 officialUrl:'https://www.eventbrite.com/e/black-and-outside-block-party-tickets-1988365122607',municipality:'Dallas',neighborhood:'Final district pending',visualTone:'social',visualIcon:'☀',
 travel:{etaMin:255,etaMax:300,parking:30,arrivalBuffer:30,destination:'Final Dallas venue pending',overnight:true,note:'Once confirmed, target arrival between 3 and 5 PM; overnight recommended.'},
 organizer:'Kay Brinae',format:'Black cultural block party with vendors, music, games and networking',bestFor:'Pure social, Black community and organic walk-around conversation',goAlone:'Yes',
 ageAccess:'All ages',attire:'Outdoor block-party casual',networkingObjective:'Speak with one organizer, one Black-owned vendor and two attendees before late-evening party energy peaks.',
 priceNotes:'Refunds listed up to seven days before the event. Official text says the venue is transitioning and final address/parking will be shared.',verifiedOn:'Official Eventbrite listing checked July 23, 2026'
},
{
 id:'hou-ghbc-procurement-fair-sep24',title:'Greater Houston Black Chamber 2026 Procurement Fair',city:'Houston',area:'Fifth Ward / Lyons Avenue',category:'career',
 start:'2026-09-24T10:00:00',end:'2026-09-24T15:00:00',displayTime:'Thu, Sep 24 · 10:00 AM–3:00 PM CT',venue:'The DeLuxe Theatre, 3303 Lyons Ave',score:96,
 tags:['BLACK-CENTERED','BUSINESS','PROCUREMENT','NETWORK','DEADLINE','CAPACITY-RISK'],audience:'Black businesses, entrepreneurs, corporate buyers, agencies, government procurement professionals and prime contractors.',
 why:'Direct buyer matchmaking, upcoming-RFP intelligence, contract-readiness sessions and B2B joint-venture networking make this materially stronger than a generic mixer for MX Ventures.',
 cost:'Early bird through Aug 22: $25 member / $45 nonmember; student $10; SGA + fair bundle $125',status:'EARLY BIRD OPEN · 28 BUNDLE SPOTS SHOWN',action:'BUY THE $125 READINESS BUNDLE',
 fit:{level:'hard',label:'Requires PTO and likely Houston lodging',note:'The fair occupies the Thursday workday; the readiness academy also requires September planning.'},scores:{career:5,social:3,black:5,writing:1,value:5},
 officialUrl:'https://ghbcc.com/event/2026procfair/',municipality:'Houston',neighborhood:'Fifth Ward · Lyons Avenue',visualTone:'career',visualIcon:'↗',
 travel:{etaMin:175,etaMax:205,parking:20,arrivalBuffer:30,destination:'The DeLuxe Theatre, 3303 Lyons Ave, Houston, TX 77020',overnight:true,note:'Take PTO; arrive in Houston the prior evening or leave Heritage Plaza before 5:45 AM.'},
 organizer:'Greater Houston Black Chamber',format:'Procurement fair, buyer matchmaking, RFP education and business networking',bestFor:'MX Ventures business development and public/corporate contracting',goAlone:'Yes — bring procurement collateral',
 attire:'Business professional',networkingObjective:'Secure buyer matchmaking, identify three upcoming RFPs and meet two potential prime-contracting partners.',
 breakInMove:'Prepare a one-page capability statement, three productized service packages, NAICS codes, certifications plan and concise examples of web, marketing and analytics outcomes.',
 priceNotes:'Early bird ends Aug 22. Matchmaking slots are first-come, first-served. The $125 bundle included four-week readiness academy access and an exclusive meet-and-greet.',verifiedOn:'Official GHBC page checked July 23, 2026',
 milestones:[{date:'2026-08-22',label:'GHBC early-bird deadline',type:'deadline'},{date:'2026-09-24',label:'GHBC Procurement Fair',type:'event'}]
}